const countries = [
  { name: 'Afghanistan', id: 1 },
  { name: 'Aland Islands', id: 2 },
  { name: 'Albania', id: 3 },
  { name: 'Algeria', id: 4 },
  { name: 'American Samoa', id: 5 },
  { name: 'Andorra', id: 6 },
  { name: 'Angola', id: 7 },
  { name: 'Anguilla', id: 8 },
  { name: 'Antarctica', id: 9 },
  { name: 'Antigua and Barbuda', id: 10 },
  { name: 'Argentina', id: 11 },
  { name: 'Armenia', id: 12 },
  { name: 'Aruba', id: 13 },
  { name: 'Australia', id: 14 },
  { name: 'Austria', id: 15 },
  { name: 'Azerbaijan', id: 16 },
  { name: 'Bahamas', id: 17 },
  { name: 'Bahrain', id: 18 },
  { name: 'Bangladesh', id: 19 },
  { name: 'Barbados', id: 20 },
  { name: 'Belarus', id: 21 },
  { name: 'Belgium', id: 22 },
  { name: 'Belize', id: 23 },
  { name: 'Benin', id: 24 },
  { name: 'Bermuda', id: 25 },
  { name: 'Bhutan', id: 26 },
  { name: 'Bolivia', id: 27 },
  { name: 'Bonaire, Sint Eustatius and Saba', id: 28 },
  { name: 'Bosnia and Herzegovina', id: 29 },
  { name: 'Botswana', id: 30 },
  { name: 'Bouvet Island', id: 31 },
  { name: 'Brazil', id: 32 },
  { name: 'British Indian Ocean Territory', id: 33 },
  { name: 'Brunei Darussalam', id: 34 },
  { name: 'Bulgaria', id: 35 },
  { name: 'Burkina Faso', id: 36 },
  { name: 'Burundi', id: 37 },
  { name: 'Cambodia', id: 38 },
  { name: 'Cameroon', id: 39 },
  { name: 'Canada', id: 40 },
  { name: 'Cape Verde', id: 41 },
  { name: 'Cayman Islands', id: 42 },
  { name: 'Central African Republic', id: 43 },
  { name: 'Chad', id: 44 },
  { name: 'Chile', id: 45 },
  { name: 'China', id: 46 },
  { name: 'Christmas Island', id: 47 },
  { name: 'Cocos (Keeling) Islands', id: 48 },
  { name: 'Colombia', id: 49 },
  { name: 'Comoros', id: 50 },
  { name: 'Congo', id: 51 },
  { name: 'Congo, Democratic Republic of the Congo', id: 52 },
  { name: 'Cook Islands', id: 53 },
  { name: 'Costa Rica', id: 54 },
  { name: "Cote D'Ivoire", id: 55 },
  { name: 'Croatia', id: 56 },
  { name: 'Cuba', id: 57 },
  { name: 'Curacao', id: 58 },
  { name: 'Cyprus', id: 59 },
  { name: 'Czech Republic', id: 60 },
  { name: 'Denmark', id: 61 },
  { name: 'Djibouti', id: 62 },
  { name: 'Dominica', id: 63 },
  { name: 'Dominican Republic', id: 64 },
  { name: 'Ecuador', id: 65 },
  { name: 'Egypt', id: 66 },
  { name: 'El Salvador', id: 67 },
  { name: 'Equatorial Guinea', id: 68 },
  { name: 'Eritrea', id: 69 },
  { name: 'Estonia', id: 70 },
  { name: 'Ethiopia', id: 71 },
  { name: 'Falkland Islands (Malvinas)', id: 72 },
  { name: 'Faroe Islands', id: 73 },
  { name: 'Fiji', id: 74 },
  { name: 'Finland', id: 75 },
  { name: 'France', id: 76 },
  { name: 'French Guiana', id: 77 },
  { name: 'French Polynesia', id: 78 },
  { name: 'French Southern Territories', id: 79 },
  { name: 'Gabon', id: 80 },
  { name: 'Gambia', id: 81 },
  { name: 'Georgia', id: 82 },
  { name: 'Germany', id: 83 },
  { name: 'Ghana', id: 84 },
  { name: 'Gibraltar', id: 85 },
  { name: 'Greece', id: 86 },
  { name: 'Greenland', id: 87 },
  { name: 'Grenada', id: 88 },
  { name: 'Guadeloupe', id: 89 },
  { name: 'Guam', id: 90 },
  { name: 'Guatemala', id: 91 },
  { name: 'Guernsey', id: 92 },
  { name: 'Guinea', id: 93 },
  { name: 'Guinea-Bissau', id: 94 },
  { name: 'Guyana', id: 95 },
  { name: 'Haiti', id: 96 },
  { name: 'Heard Island and McDonald Islands', id: 97 },
  { name: 'Holy See (Vatican City State)', id: 98 },
  { name: 'Honduras', id: 99 },
  { name: 'Hong Kong', id: 100 },
  { name: 'Hungary', id: 101 },
  { name: 'Iceland', id: 102 },
  { name: 'India', id: 103 },
  { name: 'Indonesia', id: 104 },
  { name: 'Iran, Islamic Republic of', id: 105 },
  { name: 'Iraq', id: 106 },
  { name: 'Ireland', id: 107 },
  { name: 'Isle of Man', id: 108 },
  { name: 'Israel', id: 109 },
  { name: 'Italy', id: 110 },
  { name: 'Jamaica', id: 111 },
  { name: 'Japan', id: 112 },
  { name: 'Jersey', id: 113 },
  { name: 'Jordan', id: 114 },
  { name: 'Kazakhstan', id: 115 },
  { name: 'Kenya', id: 116 },
  { name: 'Kiribati', id: 117 },
  { name: "Korea, Democratic People's Republic of", id: 118 },
  { name: 'Korea, Republic of', id: 119 },
  { name: 'Kosovo', id: 120 },
  { name: 'Kuwait', id: 121 },
  { name: 'Kyrgyzstan', id: 122 },
  { name: "Lao People's Democratic Republic", id: 123 },
  { name: 'Latvia', id: 124 },
  { name: 'Lebanon', id: 125 },
  { name: 'Lesotho', id: 126 },
  { name: 'Liberia', id: 127 },
  { name: 'Libyan Arab Jamahiriya', id: 128 },
  { name: 'Liechtenstein', id: 129 },
  { name: 'Lithuania', id: 130 },
  { name: 'Luxembourg', id: 131 },
  { name: 'Macao', id: 132 },
  { name: 'Macedonia, the Former Yugoslav Republic of', id: 133 },
  { name: 'Madagascar', id: 134 },
  { name: 'Malawi', id: 135 },
  { name: 'Malaysia', id: 136 },
  { name: 'Maldives', id: 137 },
  { name: 'Mali', id: 138 },
  { name: 'Malta', id: 139 },
  { name: 'Marshall Islands', id: 140 },
  { name: 'Martinique', id: 141 },
  { name: 'Mauritania', id: 142 },
  { name: 'Mauritius', id: 143 },
  { name: 'Mayotte', id: 144 },
  { name: 'Mexico', id: 145 },
  { name: 'Micronesia, Federated States of', id: 146 },
  { name: 'Moldova, Republic of', id: 147 },
  { name: 'Monaco', id: 148 },
  { name: 'Mongolia', id: 149 },
  { name: 'Montenegro', id: 150 },
  { name: 'Montserrat', id: 151 },
  { name: 'Morocco', id: 152 },
  { name: 'Mozambique', id: 153 },
  { name: 'Myanmar', id: 154 },
  { name: 'Namibia', id: 155 },
  { name: 'Nauru', id: 156 },
  { name: 'Nepal', id: 157 },
  { name: 'Netherlands', id: 158 },
  { name: 'Netherlands Antilles', id: 159 },
  { name: 'New Caledonia', id: 160 },
  { name: 'New Zealand', id: 161 },
  { name: 'Nicaragua', id: 162 },
  { name: 'Niger', id: 163 },
  { name: 'Nigeria', id: 164 },
  { name: 'Niue', id: 165 },
  { name: 'Norfolk Island', id: 166 },
  { name: 'Northern Mariana Islands', id: 167 },
  { name: 'Norway', id: 168 },
  { name: 'Oman', id: 169 },
  { name: 'Pakistan', id: 170 },
  { name: 'Palau', id: 171 },
  { name: 'Palestinian Territory, Occupied', id: 172 },
  { name: 'Panama', id: 173 },
  { name: 'Papua New Guinea', id: 174 },
  { name: 'Paraguay', id: 175 },
  { name: 'Peru', id: 176 },
  { name: 'Philippines', id: 177 },
  { name: 'Pitcairn', id: 178 },
  { name: 'Poland', id: 179 },
  { name: 'Portugal', id: 180 },
  { name: 'Puerto Rico', id: 181 },
  { name: 'Qatar', id: 182 },
  { name: 'Reunion', id: 183 },
  { name: 'Romania', id: 184 },
  { name: 'Russian Federation', id: 185 },
  { name: 'Rwanda', id: 186 },
  { name: 'Saint Barthelemy', id: 187 },
  { name: 'Saint Helena', id: 188 },
  { name: 'Saint Kitts and Nevis', id: 189 },
  { name: 'Saint Lucia', id: 190 },
  { name: 'Saint Martin', id: 191 },
  { name: 'Saint Pierre and Miquelon', id: 192 },
  { name: 'Saint Vincent and the Grenadines', id: 193 },
  { name: 'Samoa', id: 194 },
  { name: 'San Marino', id: 195 },
  { name: 'Sao Tome and Principe', id: 196 },
  { name: 'Saudi Arabia', id: 197 },
  { name: 'Senegal', id: 198 },
  { name: 'Serbia', id: 199 },
  { name: 'Serbia and Montenegro', id: 200 },
  { name: 'Seychelles', id: 201 },
  { name: 'Sierra Leone', id: 202 },
  { name: 'Singapore', id: 203 },
  { name: 'St Martin', id: 204 },
  { name: 'Slovakia', id: 205 },
  { name: 'Slovenia', id: 206 },
  { name: 'Solomon Islands', id: 207 },
  { name: 'Somalia', id: 208 },
  { name: 'South Africa', id: 209 },
  { name: 'South Georgia and the South Sandwich Islands', id: 210 },
  { name: 'South Sudan', id: 211 },
  { name: 'Spain', id: 212 },
  { name: 'Sri Lanka', id: 213 },
  { name: 'Sudan', id: 214 },
  { name: 'Suriname', id: 215 },
  { name: 'Svalbard and Jan Mayen', id: 216 },
  { name: 'Swaziland', id: 217 },
  { name: 'Sweden', id: 218 },
  { name: 'Switzerland', id: 219 },
  { name: 'Syrian Arab Republic', id: 220 },
  { name: 'Taiwan, Province of China', id: 221 },
  { name: 'Tajikistan', id: 222 },
  { name: 'Tanzania, United Republic of', id: 223 },
  { name: 'Thailand', id: 224 },
  { name: 'Timor-Leste', id: 225 },
  { name: 'Togo', id: 226 },
  { name: 'Tokelau', id: 227 },
  { name: 'Tonga', id: 228 },
  { name: 'Trinidad and Tobago', id: 229 },
  { name: 'Tunisia', id: 230 },
  { name: 'Turkey', id: 231 },
  { name: 'Turkmenistan', id: 232 },
  { name: 'Turks and Caicos Islands', id: 233 },
  { name: 'Tuvalu', id: 234 },
  { name: 'Uganda', id: 235 },
  { name: 'Ukraine', id: 236 },
  { name: 'United Arab Emirates', id: 237 },
  { name: 'United Kingdom', id: 238 },
  { name: 'United States', id: 239 },
  { name: 'United States Minor Outlying Islands', id: 240 },
  { name: 'Uruguay', id: 241 },
  { name: 'Uzbekistan', id: 242 },
  { name: 'Vanuatu', id: 243 },
  { name: 'Venezuela', id: 244 },
  { name: 'Viet Nam', id: 245 },
  { name: 'Virgin Islands, British', id: 246 },
  { name: 'Virgin Islands, U.s.', id: 247 },
  { name: 'Wallis and Futuna', id: 248 },
  { name: 'Western Sahara', id: 249 },
  { name: 'Yemen', id: 250 },
  { name: 'Zambia', id: 251 },
  { name: 'Zimbabwe', id: 252 },
];

export default countries;
